name: foo

on:
  workflow_dispatch:
jobs:
  ecr-repo:
    name: Oh nononono
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: bar
        id: build-image
        env:
          ENVVAR: yepyep
        run: |
          export IMAGE="$ENVVAR"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
  job2:
    name: OH yes
    runs-on: ubuntu-latest
    needs: ecr-repo
    steps:
      - name: Gimmmee
        id: aws
        run: |
          echo ${{needs.ecr-repo.outputs.image}}
          
