name: foo

on:
  workflow_dispatch:
jobs:
  ecr-repo:
    name: Oh nononono
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: bar
        id: build-image
        env:
          EV0: aaaa
          EV1: bbbb
          EV2: cccc
        run: |
          export IMAGE="$EV0/$EV1:$EV2"
          echo $IMAGE
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
      - name: print-output
        run: |
          echo $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
  job2:
    name: OH yes
    runs-on: ubuntu-latest
    needs: ecr-repo
    steps:
      - name: Gimmmee
        id: aws
        run: |
          echo ${{needs.ecr-repo.outputs.image}}
          
